### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by HenrikThien** [has-taiar/Reachability.Net#1]
Hi,
just tested it. First code which is actually working for me ^^..
But we should be able to change the timeout time for a request.
- idk, but isn't it better to change the "public bool IsHostReachable (string host = null)" to an async method and await the task inside it?
- Add some comments to the source code please :smile: 

Cheers,
Henrik

**Comment by has-taiar** [comment]
Thanks Henrik, good to see somebody is using the library :)
I actually found a package that is more extensive than Reachability.Net and it has all the features you mentioned, you can find it here (https://www.nuget.org/packages/Xam.Plugin.Connectivity/)
So I do not think I will add more features to this project :)
Thanks
