### ISSUE TITLE
Mobile Data

### ISSUE THREAD

**Issue by gustaveracosta** [has-taiar/Reachability.Net#3]
If wifi is switched on, it returns false for mobile data, even though mobile data is true/enabled.
Also, which I find quite weird, if the mobile data for the phone is enabled but it is disabled for the app, mobile data returns true/enabled.

**Comment by kuldeep34** [comment]
I am facing same issue listed in above comment, When wifi is switched on, it always returns false although Mobile Data is Enabled.

**Comment by has-taiar** [comment]
Thanks for reporting this guys,
The library uses the Reachability class provided by Xamarin. Although these behaviours seem odd, I have seen them when using the library too.

I m afraid I don't have a solution for it or time to investigate further, happy to take a a pull request if u have a solution in mind

**Comment by gustaveracosta** [comment]
Yes, I don't think there is a way around this. The method network.tryoutflags will always return with the flag wifi. It is more concerned with connectivity than reporting what is enabled or disabled. Tks though for the library, very useful
